import PlayerPlanFeedback from '../player/PlayerPlanFeedback';
import { isLegacyGenericPlan, parsePlanLines, parseWeeklySchedule, planSourceLabel } from '../../utils/planDisplay';

function SectionBlock({ title, accent, children }) {
  return (
    <div className={`mt-4 rounded-lg border p-4 ${accent}`}>
      <p className="font-headline text-[10px] font-bold uppercase tracking-[0.2em] text-[#ff7524]">{title}</p>
      <div className="mt-3">{children}</div>
    </div>
  );
}

function DayRow({ day, detail }) {
  return (
    <li className="flex gap-3 border-b border-white/5 py-2.5 last:border-0">
      {day ? (
        <span className="w-16 shrink-0 font-headline text-[10px] font-bold uppercase tracking-wide text-[#ff7524]">
          {day.slice(0, 3)}
        </span>
      ) : null}
      <span className="text-xs leading-relaxed text-slate-300">{detail}</span>
    </li>
  );
}

export default function CoachPlanCard({ plan, studentName, onPublish, onRegenerate, onDelete, busyId }) {
  const legacy = isLegacyGenericPlan(plan);
  const schedule = parseWeeklySchedule(plan.exercises);
  const goalLines = parsePlanLines(plan.goals);
  const busy = busyId === plan._id;

  return (
    <li className="midnight-asymmetric border border-player-inner/40 bg-player-container p-5 text-sm shadow-player-card">
      <p className="mb-1 font-headline text-[10px] font-bold uppercase tracking-[0.2em] text-[#ff7524]">
        {plan.isAutoGenerated ? 'Evaluation-based plan' : 'Manual plan'} · {studentName}
      </p>

      <div className="mb-2 flex items-start justify-between gap-3">
        <h3 className="font-display text-2xl leading-tight tracking-[0.06em] text-white md:text-3xl">{plan.title}</h3>
        <span
          className={`shrink-0 rounded-full px-2.5 py-1 font-orbitron text-[10px] uppercase tracking-widest ${
            plan.status === 'draft' ? 'bg-amber-500/20 text-amber-200' : 'bg-player-green/10 text-player-green'
          }`}
        >
          {plan.status}
          {plan.isAutoGenerated ? ' · auto' : ''}
        </span>
      </div>

      <p className="text-[10px] uppercase tracking-[0.18em] text-slate-500">
        {planSourceLabel(plan)} · week of {new Date(plan.weekStartDate).toLocaleDateString()}
      </p>

      {legacy ? (
        <div className="mt-4 rounded-lg border border-amber-500/40 bg-amber-500/10 px-3 py-3">
          <p className="text-xs font-medium text-amber-100">
            This is an old generic draft (before skill analysis). Regenerate to build a plan from the latest evaluation.
          </p>
          <div className="mt-3 flex flex-wrap gap-2">
            {onRegenerate ? (
              <button
                type="button"
                disabled={busy}
                onClick={() => onRegenerate(plan)}
                className="bg-[#ff7524] px-3 py-1.5 font-headline text-[10px] uppercase tracking-wider text-black disabled:opacity-50"
              >
                {busy ? 'Working…' : 'Regenerate from evaluation'}
              </button>
            ) : null}
            {onDelete && plan.status === 'draft' ? (
              <button
                type="button"
                disabled={busy}
                onClick={() => onDelete(plan._id)}
                className="border border-red-500/40 px-3 py-1.5 font-headline text-[10px] uppercase tracking-wider text-red-300 disabled:opacity-50"
              >
                Delete draft
              </button>
            ) : null}
          </div>
        </div>
      ) : null}

      {plan.playerInsights ? (
        <SectionBlock title="Player feedback preview" accent="border-[#ff7524]/20 bg-[#ff7524]/5">
          <PlayerPlanFeedback insights={plan.playerInsights} />
        </SectionBlock>
      ) : null}

      {plan.analysisSummary && !legacy ? (
        <SectionBlock title="Coach skill analysis" accent="border-player-inner/50 bg-player-bg/40">
          <pre className="whitespace-pre-wrap text-xs leading-relaxed text-slate-300">{plan.analysisSummary}</pre>
        </SectionBlock>
      ) : null}

      {goalLines.length && !legacy ? (
        <SectionBlock title="This week's goals" accent="border-player-inner/50 bg-player-bg/30">
          <ul className="space-y-2">
            {goalLines.map((line) => (
              <li key={line} className="flex gap-2 text-xs text-slate-300">
                <span className="text-[#ff7524]">▸</span>
                <span>{line.replace(/^[-•]\s*/, '')}</span>
              </li>
            ))}
          </ul>
        </SectionBlock>
      ) : null}

      {schedule.length && !legacy ? (
        <SectionBlock title="Weekly program" accent="border-player-inner/50 bg-player-bg/30">
          <ul>
            {schedule.map((row, i) => (
              <DayRow key={`${row.day}-${i}`} day={row.day} detail={row.detail} />
            ))}
          </ul>
        </SectionBlock>
      ) : null}

      {legacy ? (
        <>
          {plan.goals ? (
            <div className="mt-3 opacity-60">
              <p className="text-[10px] uppercase text-slate-500">Old goals (placeholder)</p>
              <pre className="mt-1 whitespace-pre-wrap text-xs text-slate-400">{plan.goals}</pre>
            </div>
          ) : null}
          {plan.exercises ? (
            <div className="mt-3 opacity-60">
              <p className="text-[10px] uppercase text-slate-500">Old program (placeholder)</p>
              <pre className="mt-1 whitespace-pre-wrap text-xs text-slate-400">{plan.exercises}</pre>
            </div>
          ) : null}
        </>
      ) : null}

      {plan.status === 'draft' ? (
        <p className="mt-4 text-xs font-medium text-amber-200">
          Draft — {studentName} cannot see this until you publish.
        </p>
      ) : (
        <p className="mt-4 text-xs text-player-green">Published — visible on player Schedule + notification sent.</p>
      )}

      <div className="mt-4 flex flex-col gap-2 sm:flex-row">
        {plan.status === 'draft' && onPublish ? (
          <button
            type="button"
            disabled={busy || legacy}
            onClick={() => onPublish(plan._id)}
            className="flex-1 bg-player-green/20 py-2.5 font-display text-sm tracking-wide text-player-green disabled:cursor-not-allowed disabled:opacity-40"
          >
            {legacy ? 'Regenerate first' : `Publish to ${studentName}`}
          </button>
        ) : null}
        {!legacy && onRegenerate && plan.status === 'draft' ? (
          <button
            type="button"
            disabled={busy}
            onClick={() => onRegenerate(plan)}
            className="flex-1 border border-[#ff7524]/40 py-2.5 font-headline text-[10px] uppercase tracking-wider text-[#ff7524] disabled:opacity-50"
          >
            Refresh from latest eval
          </button>
        ) : null}
      </div>
    </li>
  );
}
