const mongoose = require('mongoose');

const trainingPlanSchema = new mongoose.Schema(
  {
    coach: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    player: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    weekStartDate: { type: Date, required: true },
    title: String,
    goals: String,
    exercises: String,
    status: { type: String, enum: ['draft', 'published'], default: 'published' },
    /** System-generated draft pending coach review */
    isAutoGenerated: { type: Boolean, default: false },
    coachReviewed: { type: Boolean, default: false },
    generationMethod: { type: String, enum: ['ai', 'rules', 'manual'], default: 'rules' },
    /** Why this plan — weak/strong skill summary from evaluation */
    analysisSummary: String,
    focusSkills: [
      {
        category: String,
        skill: String,
        score: Number,
        priority: { type: String, enum: ['critical', 'needs_work', 'maintain', 'unknown'] },
      },
    ],
    /** Player message: what to improve vs what's going well */
    playerInsights: {
      criteria: { type: mongoose.Schema.Types.Mixed },
      improveMost: [
        {
          category: String,
          skill: String,
          score: Number,
          level: String,
          hint: String,
          practiceDrill: String,
        },
      ],
      doingWell: [
        {
          category: String,
          skill: String,
          score: Number,
          level: String,
          hint: String,
          practiceDrill: String,
        },
      ],
      overallAvg: Number,
      notificationTitle: String,
      notificationBody: String,
      playerMessage: String,
    },
    generationMeta: {
      provider: String,
      model: String,
      generatedAt: Date,
      latencyMs: Number,
      reasonCode: String,
      evaluationWeek: Date,
      evaluationId: String,
    },
  },
  { timestamps: true }
);

trainingPlanSchema.index({ coach: 1, player: 1, weekStartDate: 1 });

module.exports = mongoose.model('TrainingPlan', trainingPlanSchema);
