/** Detect pre–skill-analysis auto drafts still stored in DB. */
export function isLegacyGenericPlan(plan) {
  if (!plan) return false;
  if (plan.analysisSummary?.trim()) return false;
  if (plan.playerInsights?.improveMost?.length || plan.playerInsights?.doingWell?.length) return false;
  if (Array.isArray(plan.focusSkills) && plan.focusSkills.length > 0) return false;

  const goals = String(plan.goals || '');
  const exercises = String(plan.exercises || '');
  return (
    goals.includes('Edit goals after assessing') ||
    exercises.includes('System draft: warm-up') ||
    (plan.isAutoGenerated && !plan.analysisSummary)
  );
}

export function parsePlanLines(text) {
  return String(text || '')
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .filter((l) => !/^(skill analysis|this week|weekly program)/i.test(l));
}

export function parseWeeklySchedule(exercises) {
  const lines = parsePlanLines(exercises);
  return lines.map((line) => {
    const match = line.match(/^([A-Za-z]+day|[A-Za-z]+):\s*(.+)/i);
    if (match) {
      return { day: match[1], detail: match[2] };
    }
    return { day: null, detail: line };
  });
}

export function planSourceLabel(plan) {
  if (plan.generationMethod === 'ai') return 'AI + evaluation data';
  if (plan.generationMethod === 'manual') return 'Manual';
  if (plan.generationMethod === 'rules') return 'Skill analysis engine';
  return 'System';
}
